### ISSUE TITLE
Can't leave Text-Edit Mode

### ISSUE THREAD

**Issue by RealDekkia** [wladi0097/gwvp#1]
## Current Behavior
After Switching into Text-Edit Mode you can't leave it. 

## Expected Behavior
Pressing ESC or clicking into an empty area to get back to the mode in which it hilights the DOM-Elements

## Steps to Reproduce 
0. Enter Text-Edit mode and change some text
1. Try to leave it
2. ¯\\\_(ツ)_/¯
3. Profit

## Environment
Tested in the latest versions of Chrome, Firefox and Edge on Windows 10

**Comment by wladi0097** [comment]
Added a dedicated menu item and a shortcut for the texteditor
